services:
  backend:
    image: ghcr.io/mariannefeng/high-five-me-backend:latest
    restart: unless-stopped
    container_name: high-five-me-backend
    expose:
      - "5000" # Only expose internally, Caddy handles external access
    environment:
      - FRONTEND_URL=https://high-five-me.com
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
    name: proxy-network
